name: Build EXE for Windows

on:
  push:
    branches:
      - main  # ou o nome da sua branch principal
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Escolha a versão do Python que você está usando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --name=juntar_pdfs main.py
      shell: cmd

    - name: Upload the executable
      uses: actions/upload-artifact@v2
      with:
        name: exe-file
        path: dist/juntar_pdfs.exe
